SELECT UNIDADE_GESTORAS.NOME AS UNIDADE_GESTORA, SERVIDORES.NOME as NOME,CIDADES.NOME AS CIDADE, FOLHA.COD_UND_GESTORA, REMUNERACAO.CPF, REMUNERACAO.MATRICULA, REMUNERACAO.VALOR,
             REMUNERACAO.COD_MES_REFERENCIA, REMUNERACAO.CARGA_HORARIA, FOLHA.DESCRICAO, FOLHA.COD_TIPO_RUBRICA
FROM (SELECT CPF, MATRICULA, CARGA_HORARIA, COD_RUBRICA_SAL, VALOR, COD_MES_REFERENCIA, MIN(remessa_parcial_id) as remessa_parcial_id
FROM EXERCICIO_2021.SICAP_DETALHAMENTO_REMUNERACAO_SERVIDORES
GROUP BY cpf, matricula, carga_horaria, cod_rubrica_sal, valor, cod_mes_referencia HAVING COUNT(cod_mes_referencia) == 05) AS REMUNERACAO
LEFT JOIN EXERCICIO_2021.SICAP_RUBRICAS_FOLHA_SERVIDORES AS FOLHA
ON REMUNERACAO.COD_RUBRICA_SAL = FOLHA.COD_RUBRICA_SAL
AND REMUNERACAO.REMESSA_PARCIAL_ID = FOLHA.REMESSA_PARCIAL_ID
LEFT JOIN EXERCICIO_2021.servidores_nome_cpf_view AS SERVIDORES
ON REMUNERACAO.CPF = SERVIDORES.CPF
LEFT JOIN PUBLIC.REMESSA_PARCIALS
ON (REMUNERACAO.REMESSA_PARCIAL_ID = REMESSA_PARCIALS.ID)
LEFT JOIN PUBLIC.REMESSAS
ON (REMESSA_PARCIALS.REMESSA_ID = REMESSAS.ID)
LEFT JOIN PUBLIC.UNIDADE_GESTORAS
ON (REMESSAS.UNIDADE_GESTORA_ID = UNIDADE_GESTORAS.ID)
LEFT JOIN PUBLIC.CIDADES
ON (UNIDADE_GESTORAS.CIDADE_ID = CIDADES.ID)
ORDER BY CPF,CIDADE,UNIDADE_GESTORA,REMUNERACAO.COD_MES_REFERENCIA,COD_TIPO_RUBRICA,DESCRICAO